# Generated by Django 5.2.1 on 2025-05-13 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('community_shepherd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.nation')),
                ('shepherd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendees', models.TextField(help_text='List of attendees')),
                ('newcomers', models.TextField(blank=True)),
                ('highlights', models.TextField()),
                ('testimonies', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='squad_photos/')),
                ('total_attendees', models.IntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squad')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
