# Generated by Django 5.2.1 on 2025-05-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendees', models.TextField(help_text='List of attendees')),
                ('visitors', models.TextField(blank=True)),
                ('highlights', models.TextField()),
                ('testimonies', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='squad_photos/')),
                ('offering', models.IntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squad')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='SquadMeeting',
        ),
    ]
