# Generated by Django 5.2.1 on 2025-05-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0002_squadreport_delete_squadmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadreport',
            name='photo',
        ),
        migrations.CreateModel(
            name='SquadReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='squad_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='squad.squadreport')),
            ],
        ),
    ]
