# Generated by Django 5.2.1 on 2025-05-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0003_remove_squadreport_photo_squadreportphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name_plural': 'Nation'},
        ),
        migrations.AlterModelOptions(
            name='squad',
            options={'verbose_name_plural': 'Squad'},
        ),
    ]
