# Generated by Django 5.0.7 on 2025-06-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0004_alter_nation_options_alter_squad_options'),
        ('user', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='shepherd',
        ),
        migrations.RemoveField(
            model_name='squadreport',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='squadreportphoto',
            name='report',
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('community_shepherd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='HarvestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.community')),
                ('shepherd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'Harvest Groups',
            },
        ),
        migrations.CreateModel(
            name='HarvestGroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendees', models.TextField(help_text='List of attendees')),
                ('visitors', models.TextField(blank=True)),
                ('highlights', models.TextField()),
                ('testimonies', models.TextField(blank=True)),
                ('offering', models.IntegerField()),
                ('harvestgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.harvestgroup')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('harvestgroup', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HarvestGroupReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='harvest_group_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='squad.harvestgroupreport')),
            ],
        ),
        migrations.CreateModel(
            name='MissionalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='missional_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.missionallocation'),
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
        migrations.DeleteModel(
            name='SquadReport',
        ),
        migrations.DeleteModel(
            name='SquadReportPhoto',
        ),
    ]
