# Generated by Django 5.0.7 on 2025-06-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0005_remove_squad_nation_remove_squad_shepherd_and_more'),
        ('user', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('hg', 'Harvest Group'), ('community', 'Community'), ('ml', 'Missional Location')], max_length=20)),
                ('target_group_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
