# Generated by Django 5.2.1 on 2025-05-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=254753011592, max_length=20),
            preserve_default=False,
        ),
    ]
