# Generated by Django 5.0.7 on 2025-06-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SHEPHERD', 'Shepherd'), ('CS', 'Community Shepherd'), ('MLS', 'Missional Location Shepherd')], max_length=20),
        ),
    ]
